#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Verificar si estamos en la raíz del proyecto o en una carpeta válida (frontend o backend)
if [ "$GIT_DIRTY" = "a" ]; then
  echo "No se ejecuta ESLint en la carpeta raíz"
else
  # Verificar si se está ejecutando desde una carpeta válida (frontend o backend)
  if ([ "$GIT_DIRTY" = "frontend" ] || [ "$GIT_DIRTY" = "backend" ]); then
    echo "Ejecutando ESLint en la carpeta $GIT_DIRTY"
    yarn --cwd "$GIT_DIRTY" lint
  else
    echo "No se puede determinar la carpeta de trabajo, asegúrate de ejecutar desde frontend o backend"
    exit 1
  fi
fi

# # Verificar el formato del mensaje de commit
# npx commitlint --edit $1